Weather:
  location: '巧家'

snowboy:
  hotwork: 'snowboy/resources/snowboy.umdl'
  sensitivity: '0.4'
#hotwork:可选sonwboy.umdl,wukong.pmdl，小白.pmdl

server:
  port: '1037'
  password: 'hust'
  debug: "True" 
#debug:是否开启服务器调试                
      
#本地音乐存放路径
LocalPlayer:
  path: "/media/sf_sharedir/CloudMusic"

xunfei_API:
  appid: '5e3b849b'
  apikey: '12ee3473d8973cba864565dafda14758'
  apisecret: 'a96a265db24fde37211b5203796f35fe'

tuling_robot:
  api_key: 'e2cd5cabca5a40618b53779b5fe197c5'

baidu_asr:
  api_key: 'B4YtVa1VWkn0vdIX9Yawx7Im'
  secret_key: 'rM7vQN2YatVrhFv1MTzepDXPWpoA4h5e'
  DEV_PID: 80001
#1537 表示识别普通话 80001:表示极速版
Baidu_tts:
  api_key: 'B4YtVa1VWkn0vdIX9Yawx7Im'
  secret_key: 'rM7vQN2YatVrhFv1MTzepDXPWpoA4h5e'
  SPD: 5                  
  PIT: 5                  
  VOL: 5                 
  AUE: 3                  
  PER: 0 
#语速，取值0-15，默认为5中语速
#音调，取值0-15，默认为5中语调
#音量，取值0-15，默认为5中音量
#3为mp3格式(默认)； 4为pcm-16k；5为pcm-8k；6为wav（内容同pcm-16k）
#度小宇=1，度小美=0，度逍遥=3，度丫丫=4 默认为度小美
#度博文=106，度小童=110，度小萌=111，度米朵=103，度小娇=5

#各种插件的选择
asr_engine: 'baidu-asr'
tts_engine: 'baidu-tts'
nlu_engine: 'unit'


email:
  email_address: '2381324877@qq.com'
  #'14769171581@163.com'
  # 要进行邮件接收的邮箱的密码。改成自己的邮箱的密码
  # 设置 -> 账户 -> POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务 -> 开启服务：POP3/SMTP服务
  # 设置 -> 账户 -> POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务 -> 生成授权码
  email_password: 'mnupufpoaclnecdh' #'yxz123456'
  #邮箱对应的pop服务器
  pop_server_host: 'pop.qq.com'
  # 邮箱对应的pop服务器的监听端口。改成自己邮箱的pop服务器的端口；qq邮箱不需要修改此值
  pop_server_port: 995
  #一次需要读取的邮件数
  read_numb: '10'
  #是否显示具体邮件内容,true：显示
  e_text: 'False' 